name: Docker Job
on: 
  push:
    branches:
      - job-in-container
jobs:
  job-in-container:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env: 
        API_URL: some-url.com
      ports: 
        - 80  
    steps:
      - name: Log image node version
        run: |
          node -v
          cat /etc/os-release
      - name: Log env
        run: echo $API_URL    
