name: Using Secrets
on: 
    push:
        branches:
            - using-secrets         
env: 
  DB_NAME: "my-db"
jobs:
    test-env-vars:
      environment: test
      runs-on: ubuntu-latest
      steps:
          - name: test environment variables
            run: |
              echo "ENV var from yaml env conf - 1" - $DB_NAME
              echo "ENV var from yaml env conf - 2" - ${{env.DB_NAME}}
              echo "ENV var from github environment settings" - ${{vars.ENV_DB_NAME}}
    test-env-secrets:
      environment: test
      runs-on: ubuntu-latest
      steps:
          - name: test environment secrets
            run: |
              echo "ENV secrets from github environment settings" - ${{secrets.MY_SECRET}}
              echo "Above echo will not print the value, since secret is actually a secret and not exposed anywhere"