name: Deploy website
on: 
    push:
        branches:
            - using-secrets
environment: test            
env: 
  DB_NAME: "my-db"
jobs:
    test-env-vars:
        runs-on: ubuntu-latest
        steps:
            - name: test environment variables
              run: |
                echo "test ENV var" - $DB_NAME
                echo "test ENV var" - ${{env.DB_NAME}}
                echo "test ENV var" - ${{env.ENV_DB_NAME}}
    test-env-secrets:
      runs-on: ubuntu-latest
      steps:
          - name: test secrets
            run: echo "test env secrets" - {{secrets.MY_SECRET}}