name: Deploy website
on: 
    push:
        branches:
            - using -secrets
env: 
  DB_NAME: "my-db"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: test environment variables
              run: echo "test ENV var"
            - name: test secrets
              run: echo "test env secrets"