name: Host/Shell info
on: workflow_dispatch
jobs:
  display-info: 
    runs-on: ubuntu-latest
    steps: 
        - name: Display files
          run:  |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
  display-info-windows: 
        runs-on: windows-latest
        steps: 
            - name: Display files
              run:  |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
      